name: getting strted
on:
  push:
    branches: [ "SAAS-3352" ]
  pull_request:
    branches: [ develop,main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          check-latest: true
      - run: go test ./... -coverprofile cover.out
      
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args:
            -Dsonar.projectVersion="${{github.run_number}}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Clean workspace 
        run: |
          rm -rf *.scannerwork
          
      
          

      
   